// GENERATED by scripts/gen_managed_params.py from smo_sim managed_params.py. Do not edit.
//
// The complete curated managed-parameter catalogue the NanoLink Config tab shows.
// Status and telemetry paths deliberately do not belong in a configuration snapshot.
//
// catalogue-sha256: 09f64bcdcbbb6cac83421f8a6b6088b5d00c62d253885801276a4eb9fb2a6899

package collector

const CatalogueSHA256 = "09f64bcdcbbb6cac83421f8a6b6088b5d00c62d253885801276a4eb9fb2a6899"

// ManagedPaths is the ordered path list, generated from the backend catalogue.
var ManagedPaths = []string{
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.RF.PhyCellID",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.RF.EARFCNDL",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.RF.EARFCNUL",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.RF.FreqBandIndicator",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.RF.DLBandwidth",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.RF.ULBandwidth",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.RF.ReferenceSignalPower",
	"Device.Services.FAPService.1.Capabilities.MaxTxPower",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.PHY.PDSCH.Pa",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.PHY.PDSCH.Pb",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.MAC.DRX.DRXEnabled",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.MAC.DRX.OnDurationTimer",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.MAC.DRX.DRXInactivityTimer",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.MAC.DRX.LongDRXCycle",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.MAC.DRX.ShortDRXCycle",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.MAC.X_8C1F64_PCH.DefaultPagingCycle",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.Mobility.IdleMode.IntraFreq.QRxLevMinSIB1",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.Mobility.IdleMode.IntraFreq.SIntraSearch",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.A2ThresholdRSRP",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.A1ThresholdRSRP",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.Hysteresis",
	"Device.Services.FAPService.1.CellConfig.LTE.RAN.Mobility.ConnMode.EUTRA.TimeToTrigger",
	"Device.ManagementServer.PeriodicInformInterval",
	"Device.X_8C1F64_DebugMgmt.Upload.AutonomousTransferCompletePolicy",
}
